### PR TITLE
Benchmarks

### PR DESCRIPTION
**Pull request by fadilm777**

### CODE REVIEW

**Review by PossiblyAShrub — CHANGES_REQUESTED** [review]
Looks good! We should get CI to pass before we merge though. It looks like CI is failing with only lint errors. (A linter is a tool which looks for common style or logic issues.) You should be able to clean up most of them with the `./scripts/fmt.sh` script.

I know you are on windows, so you may have some issues running that script. Make sure you are using a bash. (Bash should have been installed with git, look for a program called "git-bash".) I think VSCode will also be able to use git bash with the [switch terminals drop-down](https://code.visualstudio.com/docs/terminal/basics#_terminal-shells).

Once you are in bash, you can format your code with the command:

```bash
$ ./scripts/fmt.sh
```

**Comment by PossiblyAShrub** [comment]
Ah, the error here is a bit cryptic...

The issue is, we include `yolov5` as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules). Because of this, you need to clone with `git clone --recursive ...`. _Git submodules are basically a repository inside of a repository_. Leaving out the `--recursive` would make git not clone the inner repository (called a submodule).

When the `yolov5` submodule is missing, we will get import errors like this one.

So, when we run the project in CI, github actions isn't cloning that submodule. The fix is to set the `submodules` option on the `actions/checkout@v3` task:

```diff
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -16,6 +16,8 @@ jobs:
 
     steps:
     - uses: actions/checkout@v3
+      with:
+        submodules: true
     - name: Set up Python 3.10
       uses: actions/setup-python@v3
       with:
```

Adding those two lines is basically the equivalent of adding the `--recursive` flag to `git clone`.

**Comment by fadilm777** [comment]
> Ah, the error here is a bit cryptic...
> 
> The issue is, we include `yolov5` as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules). Because of this, you need to clone with `git clone --recursive ...`. _Git submodules are basically a repository inside of a repository_. Leaving out the `--recursive` would make git not clone the inner repository (called a submodule).
> 
> When the `yolov5` submodule is missing, we will get import errors like this one.
> 
> So, when we run the project in CI, github actions isn't cloning that submodule. The fix is to set the `submodules` option on the `actions/checkout@v3` task:
> 
> ```diff
> --- a/.github/workflows/tests.yml
> +++ b/.github/workflows/tests.yml
> @@ -16,6 +16,8 @@ jobs:
>  
>      steps:
>      - uses: actions/checkout@v3
> +      with:
> +        submodules: true
>      - name: Set up Python 3.10
>        uses: actions/setup-python@v3
>        with:
> ```
> 
> Adding those two lines is basically the equivalent of adding the `--recursive` flag to `git clone`.

So, Github actions clones the entire repository in order to run the checks?

**Comment by PossiblyAShrub** [comment]
Yes. CI runs on essentially a fresh machine (think about the first time you had multipass setup.) One of the first steps is then to clone the repository onto that new machine.

I know it's confusing that even though Github hosts our code, the CI machines don't start with our code on it. So we need to tell the machine to `git clone` the repository. This is abstracted away in the `actions/checkout` task.

---

Thanks for the updates! I think it's ready to be merged.

**Pull request merged**
